project:
  type: website

website:
  title: ""
  site-url: https://sulthankarimov.my.id/myblog
  favicon: assets/img/logo_S.png
  navbar:
    logo: assets/img/logo_cropped.png
    search: true
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sakarimov
      - icon: twitter
        href: https://twitter.com/sulthan_karimov
      - icon: linkedin
        href: https://linkedin.com/in/sulthankarimov
      - icon: rss
        href: index.xml
  sidebar:
    contents: auto
    style: floating
  back-to-top-navigation: true
  reader-mode: true
format:
  html:
    theme: brite
    css: assets/css/styles.css
    toc: true
    toc-depth: 4
    toc-location: right
    title-block-categories: false

babelquarto:
  languagecodes:
  - name: id
    text: "Bahasa"
  - name: en
    text: "English"
  mainlanguage: 'en'
  languages: ['id']
title-id: ""
description-id: ""
author-id: Sulthan A. Karimov
lang: en
