project:
  type: website

website:
  title: "Sulthan A. Karimov"
  site-url: https://sulthankarimov.my.id/myblog
  description: "just another attempt to share"
  navbar:
    search: true
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sakarimov
      - icon: twitter
        href: https://twitter.com/sulthan_karimov
      - icon: linkedin
        href: https://linkedin.com/in/sulthankarimov
      - icon: rss
        href: index.xml
  sidebar:
    contents: auto
    style: floating
  back-to-top-navigation: true
  reader-mode: true
format:
  html:
    theme: litera
    css: styles.css



