name: Render & Deploy Multilingual Site
permissions: write-all

on:
  push:
    branches: [main]

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.4.550"

      - name: Install babelquarto
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            github::ropensci-review-tools/babelquarto@a485fea

      - name: Debug — list files
        run: |
          pwd
          tree -L 2

      - name: Install Jupyter for Python rendering
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install jupyter nbformat

      # -------- FIXED SECTION --------
      - name: Render multilingual site with babelquarto
        working-directory: myblog
        run: Rscript -e 'babelquarto::render_website()'   # ./myblog/_quarto.yml found  :contentReference[oaicite:1]{index=1}

      - name: Archive book render
        uses: actions/upload-artifact@v4
        with:
          name: book_render
          path: myblog/_site/

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: myblog/_site           # deploy sub-dir
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

